# Generated by Django 3.2 on 2021-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcjoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcardholder',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Previous/Current Job and Industry'),
        ),
    ]
