# Generated by Django 3.2 on 2021-08-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcjoin', '0002_alter_goldcardholder_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcardholder',
            name='roles',
            field=models.ManyToManyField(blank=True, to='gcjoin.GoldCardRole'),
        ),
    ]
